stages:
  - build
  - train
  - report

variables:
    DOCKERFILE: '.devcontainer/Dockerfile'
    IMG_NAME: 'base'
    BUILD_CONTEXT: '.'
    CACHE_REGISTRY: 'developer/jupyter-huggingface-tapelegen'
    IMAGE_REGISTRY: $CI_REGISTRY_IMAGE

dev-image:
  stage: build
  services:    
    - name: docker:dind
      command: ["--tls=false"]
  tags:
    - aime
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CACHE_REGISTRY/$IMG_NAME:$CI_COMMIT_REF_NAME || true
    - docker pull $CACHE_REGISTRY/$IMG_NAME:dev || true
    - docker build
      -f $DOCKERFILE
      --cache-from $CACHE_REGISTRY/$IMG_NAME:$CI_COMMIT_REF_NAME
      --cache-from $CACHE_REGISTRY/$IMG_NAME:dev
      --build-arg BUILDKIT_INLINE_CACHE=1
      --tag $IMAGE_REGISTRY/$IMG_NAME:$CI_COMMIT_SHA
      --tag $IMAGE_REGISTRY/$IMG_NAME:$CI_COMMIT_REF_NAME
      --target $IMG_NAME
      $BUILD_CONTEXT
    - docker push $IMAGE_REGISTRY/$IMG_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_REGISTRY/$IMG_NAME:$CI_COMMIT_REF_NAME
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_TLS_CERTDIR: ""

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE


dvc-repro:
  stage: train
  image: $IMAGE_REGISTRY/$IMG_NAME:$CI_COMMIT_SHA
  tags:
    - aime
  cache:
    paths:
      - .venv
      - .cache
  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git config user.email "cml@gitlab.wogra.com"
    - git config user.name "Gitlab CML"
    - bash create_minio_credentials.sh
    - bash scripts/install-dev-tools.sh
  script:
    - source .venv/bin/activate
    - bash auto-dvc-commit.sh
  timeout: 24h

cml:
  stage: report
  image: iterativeai/cml:0-dvc3-base1 # Python, DVC, & CML pre-installed
  before_script:
    - bash create_minio_credentials.sh
  script:
    - git fetch --depth=1 origin main
    - latest_commit=$(git rev-parse origin/main)
    - echo "$latest_commit"
    
    - dvc pull
    - dvc repro
    - dvc metrics show
    - dvc metrics diff $latest_commit
    - dvc metrics diff --md $latest_commit >> report.md
    - echo '![](./plots/losses.png "Training Losses")' >> report.md
    - echo '![](./plots/accuracies.png "Training Accuracies")' >> report.md
    
    - cml comment create report.md
