stages:
  - learn

dvc-repro-and-push:
  image: ludwigai/ludwig-ray-gpu:0.7.4
  stage: learn
  tags:
    - aime
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  script:
    - ls -al
    - git status
    - git init
    - git rm cml-dvc-repro.sh
    - git add -u
    - git commit -m "Remove cml-dvc-repro.sh"
    - cd .git
    - ls -al
    - git config user.email "cml@gitlab.wogra.com"
    - git config user.name "Gitlab CML"
    - cd ..
    - dvc pull || true
