stages:
  - learn

dvc-repro-and-push:
  image: ludwigai/ludwig-ray-gpu:0.7.4
  stage: learn
  tags:
    - aime
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  script:
    - ls -al
