stages:
  - report

cml:
  stage: report
  image: iterativeai/cml:0-dvc2-base1 # Python, DVC, & CML pre-installed
  before_script:
    - bash create_minio_credentials.sh
  script:
    - dvc pull

    - echo "## Metrics workflow vs. main" >> report.md
    - git fetch --depth=1 origin main:main
    - dvc metrics diff --show-md main >> report.md

    - echo "## My Plots" >> report.md
    
    - dvc plots diff --target Accuracy --show-vega main > vega.json
    - cat vega.json
    - vl2png vega.json > plot2.png
    - echo '![](./plot2.png "Accuracy")' >> report.md

    - cml comment create report.md
  artifacts:
    paths:
      - vega.json