stages:
  - train

dvc-repro:
  image: ludwigai/ludwig-ray-gpu:0.7.4
  stage: train
  tags:
    - aime
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git config user.email "cml@gitlab.wogra.com"
    - git config user.name "Gitlab CML"
    - bash create_minio_credentials.sh
    - pip install -r requirements.txt
  script:
    - bash auto-dvc-commit.sh

