stages:
  - train
  - report

dvc-repro:
  stage: train
  image: ludwigai/ludwig-ray-gpu:0.7.4
  tags:
    - aime
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git config user.email "cml@gitlab.wogra.com"
    - git config user.name "Gitlab CML"
    - bash create_minio_credentials.sh
    - pip install -r requirements.txt
  script:
    - bash auto-dvc-commit.sh

cml:
  stage: report
  image: iterativeai/cml:0-dvc2-base1 # Python, DVC, & CML pre-installed
  before_script:
    - bash create_minio_credentials.sh
  script:
    - git fetch --depth=1 origin main
    - latest_commit=$(git rev-parse origin/main)
    - echo "$latest_commit"dd`dd`
    
    - dvc pull
    - dvc repro
    - dvc metrics show
    - dvc metrics diff $latest_commit
    - dvc metrics diff --show-md $latest_commit >> report.md

    - cml comment create report.md
