stages:
  load:
    cmd: PYTHONPATH="." python3 src/load.py
    params:
      - data.remote.s3_endpoint_url
      - data.remote.s3_bucket
      - data.remote.s3_path
      - data.select
      - data.seed
    deps:
      - src/load.py
    outs:
      - data/load.dir

  prepare:
    cmd: PYTHONPATH="." python src/prepare.py
    params:
      - data.test-size
      - data.train-size
      - data.seed
      - data.logging_file
    deps:
      - data/load.dir
      - src/shared/data.py
      - src/shared/helpers.py
      - src/prepare.py
    outs:
      - data/prepare.dir
    metrics:
      - data/data.json

  search:
    cmd: PYTHONPATH="." python src/search.py
    params:
      - model.checkpoint
      - trainer.learning_rate
      - trainer.per_device_train_batch_size
      - trainer.per_device_eval_batch_size
      - trainer.num_train_epochs
      - trainer.warmup_ratio
      - trainer.gradient_accumulation_steps
      - trainer.loading_steps
      - trainer.logging_steps
      - data.seed
      - hyperparameters.labels_per_category
      - hyperparameters.learning_rates
      - hyperparameters.batch_sizes
      - asha.max_t
      - asha.grace_period
      - asha.reduction_factor
      - asha.trial_cpus
      - asha.trial_gpus
      - asha.n_trials
    deps:
      - data/prepare.dir
      - src/shared/data.py
      - src/shared/helpers.py
      - src/shared/learning.py
      - src/search.py
    outs:
      - data/search.dir

  train:
    cmd: PYTHONPATH="." python src/train.py
    params:
      - data.seed
      - model.checkpoint
      - model.labels_per_category
      - model.logging_file
      - trainer.learning_rate
      - trainer.per_device_train_batch_size
      - trainer.per_device_eval_batch_size
      - trainer.num_train_epochs
      - trainer.warmup_ratio
      - trainer.gradient_accumulation_steps
      - trainer.loading_steps
      - trainer.logging_steps
    deps:
      - data/search.dir
      - src/shared/helpers.py
      - src/shared/learning.py
      - src/train.py
    outs:
      - data/train.dir
    metrics:
      - data/model.json

  eval:
    cmd: PYTHONPATH="." python src/eval.py
    params:
      - model.checkpoint
      - model.labels_per_category
      - model.logging_file
      - report.logging_file
    deps:
      - data/train.dir
      - src/shared/helpers.py
      - src/shared/learning.py
      - src/eval.py
    outs:
      - data/eval.dir
    metrics:
      - data/report.json
    plots:
      - plots/eval_loss.png
      - plots/eval_accuracy.png
      - plots/data.png