stages:
  load:
    cmd: PYTHONPATH="." python3 src/load.py
    params:
      - data.remote.s3_endpoint_url
      - data.remote.s3_bucket
      - data.remote.s3_path
    deps:
      - src/load.py
    outs:
      - data/load.dir
  prepare:
    cmd: PYTHONPATH="." python src/prepare.py
    deps:
      - data/load.dir
      - src/prepare.py
    outs:
      - data/prepare.dir
  train:
    cmd: PYTHONPATH="." python src/train.py
    params:
      - model.checkpoint
      - model.eval-test-size
      - model.test-size
      - model.seed
      - model.batch_size
      - model.num_train_epochs
      - model.learning_rate
      - model.warmup_ratio
      - model.loading_steps
      - model.gradient_accumulation_steps
      - model.logging_steps
    deps:
      - data/prepare.dir
      - src/train.py
    outs:
      - data/train.dir
  evaluate:
    cmd: PYTHONPATH="." python src/eval.py
    deps:
      - data/train.dir
      - src/train.py
      - src/eval.py
plots:
  - Accuracy:
      x: 
        data/accuracy.json: epoch
      y: 
        data/accuracy.json: eval_accuracy
      x_label: Epoch
      y_label: Accuracy
  - LossFunction:
      x: 
        data/loss.json: epoch
      y: 
        data/loss.json: eval_loss
      x_label: Epoch
      y_label: Loss Function
  - ConfusionMatrix:
          x: 
            data/cm.json: actual_label
          y: 
            data/cm.json: predicted_label
          title: Confusion Matrix for Test Data
          template: confusion
          x_label: Actual label
          y_label: Predicted label
  - CondusionMatrixNormalized:
          x: 
            data/cm.json: actual_label
          y: 
            data/cm.json: predicted_label
          title: Confusion Matrix for Test Data (Normalized)
          template: confusion_normalized
          x_label: Actual label
          y_label: Predicted label
metrics:
  - data/metrics.json
