stages:
  load:
    cmd: PYTHONPATH="." python3 src/load.py
    params:
      - data.remote.s3_endpoint_url
      - data.remote.s3_bucket
      - data.remote.s3_path
      - data.select
      - data.seed
    deps:
      - src/load.py
    outs:
      - data/load.dir

  prepare:
    cmd: PYTHONPATH="." python src/prepare.py
    params:
      - data.development-size
      - data.development-train-size
      - data.seed
    deps:
      - data/load.dir
      - src/prepare.py
    outs:
      - data/prepare.dir
    metrics:
      - data.json

  train:
    cmd: PYTHONPATH="." python src/train.py
    params:
      - model.checkpoint
      - model.eval-test-size
      - model.test-size
      - model.seed
      - model.batch_size
      - model.num_train_epochs
      - model.learning_rate
      - model.warmup_ratio
      - model.loading_steps
      - model.gradient_accumulation_steps
      - model.logging_steps
      - model.hyperparameters.learning_rate_min
      - model.hyperparameters.learning_rate_max
      - model.hyperparameters.batch_sizes
      - model.asha.max_t
      - model.asha.grace_period
      - model.asha.reduction_factor
      - model.asha.trial_cpus
      - model.asha.trial_gpus
      - model.asha.n_trials
    deps:
      - data/prepare.dir
      - src/train.py
    outs:
      - data/train.dir

  evaluate:
    cmd: PYTHONPATH="." python src/eval.py
    deps:
      - data/train.dir
      - src/eval.py
    plots:
      - accuracy.json
      - loss.json
    metrics:
      - metrics.json

plots:
  - ConfusionMatrix:
          x: 
            data/train.dir/tested_labels.json: actual_label
          y: 
            data/train.dir/tested_labels.json: predicted_label
          title: Confusion Matrix for Test Data
          template: confusion
          x_label: Actual label
          y_label: Predicted label
  - ConfusionMatrixNormalized:
          x: 
            data/train.dir/tested_labels.json: actual_label
          y: 
            data/train.dir/tested_labels.json: predicted_label
          title: Confusion Matrix for Test Data (Normalized)
          template: confusion_normalized
          x_label: Actual label
          y_label: Predicted label

