data:
  remote:
    s3_endpoint_url: 'https://storage.s3.mlops.wogra.com'
    s3_bucket: 'data'
    s3_path: 'dlr/Tapelegedaten2023.zip'
  select: 6666
  development-size: 0.67
  development-train-size: 0.9
  seed: 42

model:
  checkpoint: 'google/vit-base-patch16-224-in21k'
  image_size: [224, 224]
  batch_size: 128
  num_train_epochs: 10
  learning_rate: 5e-5
  warmup_ratio: 0.1
  loading_steps: 10
  gradient_accumulation_steps: 4
  logging_steps: 10
  hyperparameters:
    learning_rate_min: 1e-6
    learning_rate_max: 1e-4
    batch_sizes: [16, 32, 64, 128]
  asha:
    max_t: 10
    grace_period: 3
    reduction_factor: 2
    trial_cpus: 1
    trial_gpus: .5
    n_trials: 5
  dataset_sizes: [3000, 2000, 1000, 600, 300, 100, 60, 30]
  seed: 42