data:
  remote:
    s3_endpoint_url: 'https://storage.s3.mlops.wogra.com'
    s3_bucket: 'data'
    s3_path: 'dlr/Tapelegedaten2023.zip'
  select: 'Complete'
  test-size: 0.3
  train-size: 0.9
  seed: 42
  logging_file: 'data.json'

trainer:
  learning_rate: 1e-5
  per_device_train_batch_size: 128
  per_device_eval_batch_size: 128
  num_train_epochs: 30
  warmup_ratio: 0.1
  gradient_accumulation_steps: 4
  loading_steps: 10
  logging_steps: 10

model:
  checkpoint: 'google/vit-base-patch16-224-in21k'
  image_size: [224, 224]
  labels_per_category: [500, 400, 300 , 200, 100]
  logging_file : 'model.json'

hyperparameters:
  labels_per_category: 256
  learning_rates: [1e-6, 1e-4]
  batch_sizes: [16, 32, 64, 128]

asha:
  max_t: 21
  grace_period: 3
  reduction_factor: 2
  trial_cpus: 1
  trial_gpus: .5
  n_trials: 30

report:
  logging_file: 'report.json'
