data:
  remote:
    s3_endpoint_url: 'https://storage.s3.mlops.wogra.com'
    s3_bucket: 'data'
    s3_path: 'dlr/Tapelegedaten2023.zip'
  select: 'Complete'
  development-size: 0.67
  development-train-size: 0.9
  seed: 42

model:
  checkpoint: 'google/vit-base-patch16-224-in21k'
  image_size: [224, 224]

trainer:
  learning_rate: 1e-5
  per_device_train_batch_size: 128
  per_device_eval_batch_size: 128
  num_train_epochs: 10
  warmup_ratio: 0.1
  gradient_accumulation_steps: 4
  loading_steps: 10
  logging_steps: 10

hyperparameters:
  data:
    seed: 42
    labels_per_category: 300
  learning_rates: [1e-6, 1e-4]
  batch_sizes: [16, 32, 64, 128]

asha:
  max_t: 10
  grace_period: 3
  reduction_factor: 2
  trial_cpus: 1
  trial_gpus: .5
  n_trials: 6

evaluate:
  data:
    seed: 42
    sizes: [2800, 1800, 1200, 800, 500, 250, 100]
