data:
  remote:
    s3_endpoint: 'https://storage.s3.mlops.wogra.com'
    s3_bucket: 'data'
    s3_path: 'dlr/my_best_tapelegen_model.zip'

  culture_id: 1
  test_train_ratio: 0.33
  random_state: 42

model:
  word_sequence_length_limit: 256
  epochs: 10
  early_stop: 3
  batch_size: 4
  learning_rate: 0.00002
  filter_tokenizer_words: 5000
  filter_token_length: 2
