data:
  remote:
    s3_endpoint_url: 'https://storage.s3.mlops.wogra.com'
    s3_bucket: 'data'
    s3_path: 'dlr/Tapelegedaten2023.zip'
  seed: 42
  select: 5000

model:
  checkpoint: 'google/vit-base-patch16-224-in21k'
  eval-test-size: 0.2
  test-size: 0.5
  seed: 42
  batch_size: 256
  num_train_epochs: 10
  learning_rate: 5e-5
  warmup_ratio: 0.1
  loading_steps: 10
  gradient_accumulation_steps: 4
  logging_steps: 10
